force-app/main/default/objects/Account/fields/Content_Key__c.field-meta.xml
<CustomField>
    <fullName>Content_Key__c</fullName>
    <description>Populated with the Content Key from Salesforce CMS</description>
    <label>Content Key</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <displayFormat>EXP-{0000}</displayFormat>
        <label>Experience Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Organization, Educational Institution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/hed__Program_Enrollment__c.object-meta.xml
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The Program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__End_Date__c</fullName>
    <description
  >The date the student is scheduled to complete the Program.</description>
    <inlineHelpText
  >The date the student is scheduled to complete the Program.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__GPA__c.field-meta.xml
<CustomField>
    <fullName>hed__GPA__c</fullName>
    <description>The student&apos;s current grade point average.</description>
    <inlineHelpText
  >The student&apos;s current grade point average.</inlineHelpText>
    <label>GPA</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description
  >The date the student started, or is expected to start, this Program.</description>
    <inlineHelpText
  >The date the student started, or is expected to start, this Program.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Test__c/hed__Test__c.object-meta.xml
<CustomObject>
    <description>An instance of a student taking a test.</description>
    <label>Test</label>
    <nameField>
        <displayFormat>TST-{0000}</displayFormat>
        <label>Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Test__c/fields/Asset_URL__c.field-meta.xml
<CustomField>
    <fullName>Asset_URL__c</fullName>
    <label>Asset URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/hed__Test__c/fields/Certification_URL__c.field-meta.xml
<CustomField>
    <fullName>Certification_URL__c</fullName>
    <label>Certification URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/hed__Test__c/fields/Content_Key__c.field-meta.xml
<CustomField>
    <fullName>Content_Key__c</fullName>
    <description>Populated with the Content Key from Salesforce CMS</description>
    <label>Content Key</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Test__c/fields/Credential_ID__c.field-meta.xml
<CustomField>
    <fullName>Credential_ID__c</fullName>
    <inlineHelpText>Enter the unique identification number or string of the exam</inlineHelpText>
    <label>Credential ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Test__c/fields/Exam_Name__c.field-meta.xml
<CustomField>
    <fullName>Exam_Name__c</fullName>
    <inlineHelpText>Enter the name of the exam passed</inlineHelpText>
    <label>Exam Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Test__c/fields/hed__Test_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Test_Date__c</fullName>
    <description
  >The date the applicant or official source indicates the test was started.</description>
    <inlineHelpText
  >The date the applicant or official source indicates the test was started.</inlineHelpText>
    <label>Test Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Test__c/fields/hed__Test_Type__c.field-meta.xml
<CustomField>
    <fullName>hed__Test_Type__c</fullName>
    <description>The formal name for the test taken.</description>
    <inlineHelpText>The formal name for the test taken.</inlineHelpText>
    <label>Test Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Professional Certification</fullName>
            </value>
            <value>
                <fullName>Skills Assessment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Test__c/fields/Issuing_Organization__c.field-meta.xml
<CustomField>
    <fullName>Issuing_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issuing Organization</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tests</relationshipLabel>
    <relationshipName>Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Professional.recordType-meta.xml
<RecordType>
    <fullName>Professional</fullName>
    <active>true</active>
    <label>Professional</label>
</RecordType>

force-app/main/default/classes/expController.cls
public with sharing class ExpController {
    private static final String PROFESSIONAL_EXPERIENCE_RECORD_TYPE_ID = '0123h000000HxFZAA0';
    private static final String VOLUNTEER_EXPERIENCE_RECORD_TYPE_ID = '0123h000000HxFeAAK';
    
    @AuraEnabled(Cacheable=true)
    public static hed__Program_Enrollment__c[] getAllProgEnroll() {
        return [
            SELECT
                Id,
                hed__GPA__c,
                hed__Start_Date__c,
                hed__End_Date__c,
                hed__Account__r.Name,
                hed__Account__r.Website,
                hed__Account__r.Parent.Parent.Name,
                hed__Account__r.Parent.Parent.Website,
                hed__Account__r.Parent.Parent.Image_URL__c,
                hed__Account__r.Parent.Parent.Content_Key__c
            FROM hed__Program_Enrollment__c
            WITH USER_MODE
            ORDER BY hed__End_Date__c DESC
        ];
    }
    
    @AuraEnabled(Cacheable=true)
    public static hed__Test__c[] getAllCerts() {
        return [
            SELECT
                Id,
                Exam_Name__c,
                hed__Test_Date__c,
                Credential_ID__c,
                Certification_URL__c,
                Issuing_Organization__r.Name,
                Asset_URL__c,
                Image_URL__c,
                Content_Key__c
            FROM hed__Test__c
            WHERE hed__Test_Type__c = 'Professional Certification'
            WITH USER_MODE
            ORDER BY hed__Test_Date__c DESC
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static hed__Test__c[] getAllSkills() {
        return [
            SELECT
                Id,
                Exam_Name__c,
                hed__Test_Date__c,
                Certification_URL__c,
                Issuing_Organization__r.Name,
                Asset_URL__c,
                Image_URL__c,
                Content_Key__c
            FROM hed__Test__c
            WHERE hed__Test_Type__c = 'Skills Assessment'
            WITH USER_MODE
            ORDER BY hed__Test_Date__c DESC
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static Experience__c[] getAllProfExp() {
        return [
            SELECT
                Id,
                Description__c,
                End_Date__c,
                Start_Date__c,
                Job_Title__c,
                Organization__r.Name,
                Organization__r.Website
            FROM Experience__c
            WHERE RecordTypeId = :PROFESSIONAL_EXPERIENCE_RECORD_TYPE_ID
            WITH USER_MODE
            ORDER BY Sort_Order__c DESC NULLS FIRST
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static Experience__c[] getAllVolExp() {
        return [
            SELECT
                Id,
                Description__c,
                End_Date__c,
                Start_Date__c,
                Job_Title__c,
                Organization__r.Name,
                Organization__r.Website
            FROM Experience__c
            WHERE RecordTypeId = :VOLUNTEER_EXPERIENCE_RECORD_TYPE_ID
            WITH USER_MODE
            ORDER BY Sort_Order__c DESC
        ];
    }
    
    @AuraEnabled(Cacheable=true)
    public static Project__c[] getAllProjects() {
        return [
            SELECT Id, Start_Date__c, End_Date__c, Description__c, Name
            FROM Project__c
            WITH USER_MODE
            ORDER BY End_Date__c DESC
        ];
    }
}